// <auto-generated />
using CS322_PZ_VukicMaja3683.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS322_PZ_VukicMaja3683.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230410153720_inition")]
    partial class inition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS322_PZ_VukicMaja3683.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FilmId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<string>("Reditelj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reditelj");

                    b.HasKey("FilmId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("CS322_PZ_VukicMaja3683.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisnikId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<bool>("Clanarina")
                        .HasColumnType("bit")
                        .HasColumnName("Clanarina");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.Property<int>("KorisnikRola")
                        .HasColumnType("int");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("CS322_PZ_VukicMaja3683.Models.Film", b =>
                {
                    b.HasOne("CS322_PZ_VukicMaja3683.Models.Korisnik", null)
                        .WithMany("KorisnikFilmovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CS322_PZ_VukicMaja3683.Models.Korisnik", b =>
                {
                    b.Navigation("KorisnikFilmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
